using System;
using System.Collections.Generic;
using System.Diagnostics;
using Godot;

public partial class FluidSimulator : Node2D
{
	private ParticleData particles;
	private SpatialHash hash;
	private PbfSolver solver;
	private FluidRenderer renderer;
	private DensityField densityField;

	// ============================================================
	// Energy
	// ============================================================

	private EnergySystem energySystem;

	// ============================================================
	// Energy statistics graph
	// ============================================================

	private StatisticsGraph statisticsGraph;

	private double energyGeneratedThisFrame = 0.0;

	// Last physics delta.
	//
	// Used by the profiler and other systems that need the
	// actual physics timestep.
	private float lastPhysicsDelta = 0.0f;

	// ============================================================
	// Current indicator
	// ============================================================

	private Sprite2D currentIndicator;
	private ShaderMaterial currentIndicatorMaterial;

	private const float CurrentGenerationThreshold = 0.0005f;

	// ============================================================
	// Maximum number of particles
	// ============================================================

	// IMPORTANT:
	//
	// This is the maximum allocated particle capacity.
	// It is NOT the intended number of active particles.
	//
	// ActiveParticleCount is particles.Count.
	private const int ParticleCount = 4000;

	// ============================================================
	// Particle statistics
	// ============================================================

	// Number of actual rain particles created since startup.
	//
	// This is NOT the number of active particles.
	// particles.Count is the current active particle count.
	//
	// Removed particles are NOT counted again as spawns.
	private long totalRainSpawns = 0;

	// ============================================================
	// Density rendering grid
	// ============================================================

	private const int DensityWidth = 360;
	private const int DensityHeight = 180;
	private const float DensityCellSize = 4.0f;

	// ============================================================
	// Simulation world
	// ============================================================

	private const float WorldWidth = 920.0f;
	private const float WorldHeight = 1020.0f;

	private const float WorldMinX = 260.0f;
	private const float WorldMaxX = 1180.0f;

	private const float WorldMinY = -200.0f;
	private const float WorldMaxY = 820.0f;

	// ============================================================
	// Dynamic Rain
	// ============================================================
	// RainAmount = 100.0f represents 50% rain.
	// Therefore 100% rain = 200 particles/sec.
	// 10% = 20/sec, 20% = 40/sec, ... 100% = 200/sec.

	private const float RainAmount = 75.0f;

	private const int RainMinimumPercent = 10;
	private const int RainMaximumPercent = 100;
	private const int RainPercentStep = 10;

	private const float RainMinimumDuration = 25.0f;
	private const float RainMaximumDuration = 60.0f;

	private int currentRainPercent;
	private float rainPhaseTimer;

	// ============================================================
	// Rain HUD
	// ============================================================

	private CanvasLayer rainHudLayer;
	private Label rainHudLabel;

	private const float RainSpawnY =
		WorldMinY;

	private const float RainVelocityX =
		0.0f;

	private const float RainVelocityY =
		250.0f;

	private float rainSpawnAccumulator =
		0.0f;

	private readonly RandomNumberGenerator rainRandom =
		new RandomNumberGenerator();

	// ============================================================
	// Despawn
	// ============================================================

	private const float DespawnLeftX =
		WorldMinX + 8.0f;

	private const float DespawnRightX =
		WorldMaxX - 8.0f;

	private const float DespawnBottomY =
		WorldMaxY - 8.0f;

	// ============================================================
	// Water wheels
	// ============================================================

	private const int MaxWheelCount = 4;

	private const int WheelTileAtlasX = 4;
	private const int WheelTileAtlasY = 7;

	private const float WheelOuterRadius = 50.0f;
	private const float WheelInnerRadius = 12.5f;

	private const int WheelBladeCount = 8;
	private const float WheelBladeWidth = 7.5f;

	private readonly List<FluidWheelState>
		wheelStates =
			new List<FluidWheelState>();

	private readonly List<WaterWheelVisual>
		wheelVisuals =
			new List<WaterWheelVisual>();

	// ============================================================
	// Wheel energy tracking
	// ============================================================

	private float[] previousWheelAngles =
		Array.Empty<float>();

	// Energy generated by each wheel during the current frame.
	private double[] wheelEnergyGeneratedThisFrame =
		Array.Empty<double>();

	// ============================================================
	// Full-frame profiler
	// ============================================================

	private const int FullProfilerInterval = 600;

	private int fullProfilerFrames = 0;

	private double fullPhysicsTime = 0.0;

	private double fullSpawnTime = 0.0;
	private double fullPbfTime = 0.0;
	private double fullDensityTime = 0.0;
	private double fullRendererTime = 0.0;

	private double fullRendererBuildPixelsTime = 0.0;
	private double fullRendererSurfaceGlowTime = 0.0;
	private double fullRendererFillBytesTime = 0.0;
	private double fullRendererTextureUploadTime = 0.0;

	// ============================================================
	// Initialization
	// ============================================================

	public override void _Ready()
	{
		rainRandom.Randomize();
		InitializeDynamicRain();

		energySystem =
			new EnergySystem();

		SetupCurrentIndicator();

		SetupStatisticsHud();
		SetupRainHud();

		particles =
			new ParticleData(
				ParticleCount
			);

		hash =
			new SpatialHash(
				ParticleCount
			);

		solver =
			new PbfSolver(
				hash
			);

		CreateWaterWheelsFromEnvironment();

		InitializeWheelEnergyTracking();

		densityField =
			new DensityField(
				DensityWidth,
				DensityHeight,
				DensityCellSize
			);

		renderer =
			new FluidRenderer();

		AddChild(
			renderer
		);

		renderer.Initialize(
			DensityWidth,
			DensityHeight,
			DensityCellSize
		);

		BuildDensityField();

		renderer.Update(
			particles,
			densityField
		);

		UpdateStatisticsHud(
			0.0f
		);
		UpdateRainHud();

		GD.Print(
			"Fluid initialized. " +
			"World=" +
			WorldWidth +
			"x" +
			WorldHeight +
			", ParticleCapacity=" +
			ParticleCount +
			", ActiveParticles=" +
			particles.Count +
			", Rain=" +
			currentRainPercent.ToString("F0") +
			"%, Wheels=" +
			wheelStates.Count +
			", Energy=" +
			energySystem.Energy.ToString("F2")
		);
	}

	// ============================================================
	// Physics
	// ============================================================

	public override void _PhysicsProcess(
		double delta)
	{
		Stopwatch physicsTimer =
			Stopwatch.StartNew();

		float dt =
			(float)delta;

		lastPhysicsDelta =
			dt;

		// --------------------------------------------------------
		// Reset per-frame energy counters
		// --------------------------------------------------------

		energyGeneratedThisFrame =
			0.0;

		if (
			wheelEnergyGeneratedThisFrame.Length !=
			wheelStates.Count)
		{
			wheelEnergyGeneratedThisFrame =
				new double[
					wheelStates.Count
				];
		}

		for (
			int i = 0;
			i < wheelEnergyGeneratedThisFrame.Length;
			i++)
		{
			wheelEnergyGeneratedThisFrame[i] =
				0.0;
		}

		// --------------------------------------------------------
		// Rain
		// --------------------------------------------------------

		Stopwatch spawnTimer =
			Stopwatch.StartNew();

		SpawnRainParticle(
			dt
		);

		UpdateRainHud();

		spawnTimer.Stop();

		fullSpawnTime +=
			spawnTimer.Elapsed.TotalMilliseconds;

		// --------------------------------------------------------
		// Additional wheel physics
		// --------------------------------------------------------

		StepAdditionalWheels(
			dt
		);

		// --------------------------------------------------------
		// PBF
		// --------------------------------------------------------

		Stopwatch pbfTimer =
			Stopwatch.StartNew();

		if (
			particles.Count > 0)
		{
			solver.Solve(
				particles,
				dt
			);
		}
		else
		{
			if (
				wheelStates.Count > 0)
			{
				wheelStates[0].Step(
					dt
				);
			}
		}

		pbfTimer.Stop();

		fullPbfTime +=
			pbfTimer.Elapsed.TotalMilliseconds;

		// --------------------------------------------------------
		// Energy + current indicator
		// --------------------------------------------------------

		bool currentGenerated =
			UpdateEnergyFromWheelRotation();

		UpdateCurrentIndicator(
			currentGenerated
		);

		// --------------------------------------------------------
		// Despawn particles
		// --------------------------------------------------------
		//
		// IMPORTANT:
		//
		// Particles leaving the simulation are permanently removed.
		// They are NOT recycled back to the rain spawn position.
		//
		// This must happen BEFORE the statistics graph is updated
		// so ActiveParticleCount represents the actual current
		// number of particles in the simulation.
		// --------------------------------------------------------

		RemoveParticlesAtOuterEdges();

		// --------------------------------------------------------
		// Update statistics graph
		// --------------------------------------------------------

		UpdateStatisticsHud(
			dt
		);

		// --------------------------------------------------------
		// Wheel visuals
		// --------------------------------------------------------

		UpdateWheelVisuals();

		// --------------------------------------------------------
		// Density
		// --------------------------------------------------------

		Stopwatch densityTimer =
			Stopwatch.StartNew();

		BuildDensityField();

		densityTimer.Stop();

		fullDensityTime +=
			densityTimer.Elapsed.TotalMilliseconds;

		// --------------------------------------------------------
		// Renderer
		// --------------------------------------------------------

		Stopwatch rendererTimer =
			Stopwatch.StartNew();

		renderer.Update(
			particles,
			densityField
		);

		rendererTimer.Stop();

		fullRendererTime +=
			rendererTimer.Elapsed.TotalMilliseconds;

		fullRendererBuildPixelsTime +=
			renderer.LastBuildPixelsMs;

		fullRendererSurfaceGlowTime +=
			renderer.LastSurfaceGlowMs;

		fullRendererFillBytesTime +=
			renderer.LastFillBytesMs;

		fullRendererTextureUploadTime +=
			renderer.LastTextureUploadMs;

		// --------------------------------------------------------
		// Profiler
		// --------------------------------------------------------

		physicsTimer.Stop();

		fullPhysicsTime +=
			physicsTimer.Elapsed.TotalMilliseconds;

		fullProfilerFrames++;

		if (
			fullProfilerFrames >=
			FullProfilerInterval)
		{
			PrintFullProfiler();

			ResetFullProfiler();
		}
	}

	// ============================================================
	// Rain HUD setup
	// ============================================================

	private void SetupRainHud()
	{
		rainHudLayer =
			new CanvasLayer();

		rainHudLayer.Layer = 20;

		rainHudLabel =
			new Label();

		rainHudLabel.Position =
			new Vector2(20.0f, 20.0f);

		rainHudLabel.AddThemeFontSizeOverride(
			"font_size",
			22
		);

		rainHudLabel.Text =
			"RAIN  --%\nNEXT CHANGE --s";

		rainHudLayer.AddChild(
			rainHudLabel
		);

		AddChild(
			rainHudLayer
		);
	}

	// ============================================================
	// Rain HUD update
	// ============================================================

	private void UpdateRainHud()
	{
		if (rainHudLabel == null)
		{
			return;
		}

		float remaining =
			Mathf.Max(
				rainPhaseTimer,
				0.0f
			);

		float currentRainAmount =
			RainAmount *
			(currentRainPercent / 50.0f);

		rainHudLabel.Text =
			"RAIN  " +
			currentRainPercent +
			"%\nRATE  " +
			currentRainAmount.ToString("F0") +
			" / sec\nNEXT CHANGE  " +
			remaining.ToString("F0") +
			"s";
	}

	// ============================================================
	// Statistics graph setup
	// ============================================================

	private void SetupStatisticsHud()
	{
		Node mainScene =
			GetTree().CurrentScene;

		if (
			mainScene == null)
		{
			GD.PushWarning(
				"FluidSimulator: CurrentScene could not be found. " +
				"Statistics graph cannot be found."
			);

			return;
		}

		// IMPORTANT:
		//
		// StatisticsGraph is now a node that already exists
		// in the scene, underneath BottomUI.
		//
		// We must NOT create another StatisticsGraph here.
		statisticsGraph =
			FindNodeOfType<StatisticsGraph>(
				mainScene
			);

		if (
			statisticsGraph == null)
		{
			GD.PushWarning(
				"FluidSimulator: StatisticsGraph could not be found " +
				"in the scene. Make sure the StatisticsGraph node " +
				"is attached to the Control under BottomUI."
			);

			return;
		}

		GD.Print(
			"FluidSimulator: Using existing StatisticsGraph: " +
			statisticsGraph.GetPath()
		);
	}

	// ============================================================
	// Statistics graph update
	// ============================================================

	private void UpdateStatisticsHud(
		float delta)
	{
		if (
			statisticsGraph == null)
		{
			return;
		}

		// Current total energy production rate.
		//
		// energyGeneratedThisFrame is the amount generated
		// during this physics frame.
		double energyPerSecond =
			delta > 0.000001f
				? energyGeneratedThisFrame / delta
				: 0.0;

		double[] wheelEnergyPerSecond =
			GetWheelEnergyPerSecondArray(
				delta
			);

		statisticsGraph.AddSample(
			ActiveParticleCount,
			energyPerSecond,
			(float)Engine.GetFramesPerSecond(),
			delta,
			wheelEnergyPerSecond
		);
	}

	// ============================================================
	// Wheel energy per second array
	// ============================================================

	private double[] GetWheelEnergyPerSecondArray(
		float delta)
	{
		double[] result =
			new double[
				wheelStates.Count
			];

		if (
			delta <= 0.000001f)
		{
			return result;
		}

		for (
			int i = 0;
			i < wheelStates.Count;
			i++)
		{
			result[i] =
				GetWheelEnergyThisFrame(i) /
				delta;
		}

		return result;
	}

	// ============================================================
	// Initialize wheel energy tracking
	// ============================================================

	private void InitializeWheelEnergyTracking()
	{
		previousWheelAngles =
			new float[
				wheelStates.Count
			];

		wheelEnergyGeneratedThisFrame =
			new double[
				wheelStates.Count
			];

		for (
			int i = 0;
			i < wheelStates.Count;
			i++)
		{
			previousWheelAngles[i] =
				wheelStates[i].Angle;

			wheelEnergyGeneratedThisFrame[i] =
				0.0;
		}
	}

	// ============================================================
	// Energy from wheel rotation
	// ============================================================

	private bool UpdateEnergyFromWheelRotation()
	{
		int wheelCount =
			wheelStates.Count;

		if (
			wheelCount <= 0)
		{
			return false;
		}

		if (
			previousWheelAngles.Length !=
			wheelCount)
		{
			InitializeWheelEnergyTracking();

			return false;
		}

		if (
			wheelEnergyGeneratedThisFrame.Length !=
			wheelCount)
		{
			wheelEnergyGeneratedThisFrame =
				new double[
					wheelCount
				];
		}

		bool currentGenerated =
			false;

		for (
			int i = 0;
			i < wheelCount;
			i++)
		{
			float currentAngle =
				wheelStates[i].Angle;

			float previousAngle =
				previousWheelAngles[i];

			float angularMovement =
				Mathf.Abs(
					Mathf.AngleDifference(
						previousAngle,
						currentAngle
					)
				);

			if (
				angularMovement >
				0.0f)
			{
				double frameEnergy =
					angularMovement *
					energySystem.EnergyPerRadian;

				energySystem.AddEnergy(
					frameEnergy
				);

				energyGeneratedThisFrame +=
					frameEnergy;

				wheelEnergyGeneratedThisFrame[i] +=
					frameEnergy;
			}

			if (
				angularMovement >
				CurrentGenerationThreshold)
			{
				currentGenerated =
					true;
			}

			previousWheelAngles[i] =
				currentAngle;
		}

		return currentGenerated;
	}

	// ============================================================
	// Public wheel energy access
	// ============================================================

	public int WheelCount =>
		wheelStates.Count;

	public double GetWheelEnergyThisFrame(
		int wheelIndex)
	{
		if (
			wheelIndex < 0 ||
			wheelIndex >=
			wheelEnergyGeneratedThisFrame.Length)
		{
			return 0.0;
		}

		return wheelEnergyGeneratedThisFrame[
			wheelIndex
		];
	}

	public double GetWheelEnergyPerSecond(
		int wheelIndex,
		float delta)
	{
		if (
			delta <= 0.000001f)
		{
			return 0.0;
		}

		return
			GetWheelEnergyThisFrame(
				wheelIndex
			) /
			delta;
	}

	// ============================================================
	// Current indicator setup
	// ============================================================

	private void SetupCurrentIndicator()
	{
		currentIndicator =
			FindNodeByName<Sprite2D>(
				GetTree().Root,
				"CurrentIndicator"
			);

		if (
			currentIndicator == null)
		{
			GD.PushWarning(
				"FluidSimulator: CurrentIndicator Sprite2D " +
				"could not be found."
			);

			return;
		}

		Shader shader =
			new Shader();

		shader.Code = @"
shader_type canvas_item;

uniform float grayscale_amount = 1.0;

void fragment()
{
	vec4 tex = texture(TEXTURE, UV);

	float gray =
		dot(
			tex.rgb,
			vec3(
				0.299,
				0.587,
				0.114
			)
		);

	vec3 result =
		mix(
			tex.rgb,
			vec3(gray),
			grayscale_amount
		);

	COLOR =
		vec4(
			result,
			tex.a
		);
}
";

		currentIndicatorMaterial =
			new ShaderMaterial();

		currentIndicatorMaterial.Shader =
			shader;

		currentIndicator.Material =
			currentIndicatorMaterial;

		SetCurrentIndicatorLit(
			false
		);
	}

	// ============================================================
	// Current indicator state
	// ============================================================

	private void UpdateCurrentIndicator(
		bool currentGenerated)
	{
		if (
			currentIndicatorMaterial == null)
		{
			return;
		}

		SetCurrentIndicatorLit(
			currentGenerated
		);
	}

	private void SetCurrentIndicatorLit(
		bool lit)
	{
		if (
			currentIndicatorMaterial == null)
		{
			return;
		}

		currentIndicatorMaterial.SetShaderParameter(
			"grayscale_amount",
			lit
				? 0.0f
				: 1.0f
		);
	}

	// ============================================================
	// Find node by name
	// ============================================================

	private static T FindNodeByName<T>(
		Node node,
		string nodeName)
		where T : Node
	{
		if (
			node is T typedNode &&
			typedNode.Name == nodeName)
		{
			return typedNode;
		}

		foreach (
			Node child in
			node.GetChildren())
		{
			T result =
				FindNodeByName<T>(
					child,
					nodeName
				);

			if (
				result != null)
			{
				return result;
			}
		}

		return null;
	}

	// ============================================================
	// Find node by type
	// ============================================================

	private static T FindNodeOfType<T>(
		Node node)
		where T : Node
	{
		if (
			node is T typedNode)
		{
			return typedNode;
		}

		foreach (
			Node child in
			node.GetChildren())
		{
			T result =
				FindNodeOfType<T>(
					child
				);

			if (
				result != null)
			{
				return result;
			}
		}

		return null;
	}

	// ============================================================
	// Public energy access
	// ============================================================

	public EnergySystem Energy =>
		energySystem;

	public double CurrentEnergy =>
		energySystem != null
			? energySystem.Energy
			: 0.0;

	public double TotalEnergyGenerated =>
		energySystem != null
			? energySystem.TotalGenerated
			: 0.0;

	// ============================================================
	// Public particle statistics
	// ============================================================

	// Current number of active particles.
	//
	// This is the number of particle slots currently present
	// in ParticleData.
	public int ActiveParticleCount =>
		particles != null
			? particles.Count
			: 0;

	// Maximum allocated particle capacity.
	public int ParticleCapacity =>
		ParticleCount;

	// Number of actual rain particles created since startup.
	//
	// Removed particles are NOT counted again.
	public long TotalRainSpawns =>
		totalRainSpawns;

	// ============================================================
	// Find Environment
	// ============================================================

	private TileMapLayer FindEnvironment()
	{
		TileMapLayer environment =
			GetNodeOrNull<TileMapLayer>(
				"../Environment"
			);

		if (
			environment != null)
		{
			return environment;
		}

		return FindEnvironmentRecursive(
			GetTree().Root
		);
	}

	private static TileMapLayer FindEnvironmentRecursive(
		Node node)
	{
		if (
			node is TileMapLayer &&
			node.Name == "Environment")
		{
			return (TileMapLayer)node;
		}

		foreach (
			Node child in
			node.GetChildren())
		{
			TileMapLayer result =
				FindEnvironmentRecursive(
					child
				);

			if (
				result != null)
			{
				return result;
			}
		}

		return null;
	}

	// ============================================================
	// Create wheels from marker tiles
	// ============================================================

	private void CreateWaterWheelsFromEnvironment()
	{
		TileMapLayer environment =
			FindEnvironment();

		if (
			environment == null)
		{
			GD.PushWarning(
				"FluidSimulator: Environment TileMapLayer " +
				"could not be found. No wheels created."
			);

			return;
		}

		GameViewMapping mapping =
			CreateGameViewMapping();

		if (
			!mapping.IsValid)
		{
			GD.PushWarning(
				"FluidSimulator: Could not establish " +
				"viewport mapping. No wheels created."
			);

			return;
		}

		IEnumerable<Vector2I> usedCells =
			environment.GetUsedCells();

		foreach (
			Vector2I cell in
			usedCells)
		{
			if (
				wheelStates.Count >=
				MaxWheelCount)
			{
				break;
			}

			int sourceId =
				environment.GetCellSourceId(
					cell
				);

			if (
				sourceId < 0)
			{
				continue;
			}

			Vector2I atlasCoords =
				environment.GetCellAtlasCoords(
					cell
				);

			if (
				atlasCoords.X !=
				WheelTileAtlasX ||
				atlasCoords.Y !=
				WheelTileAtlasY)
			{
				continue;
			}

			Vector2 tileCenterLocal =
				environment.MapToLocal(
					cell
				);

			Vector2 tileCenterGlobal =
				environment.ToGlobal(
					tileCenterLocal
				);

			Vector2 simulationPosition =
				mapping.ToSimulationSpace(
					tileCenterGlobal
				);

			CreateWaterWheel(
				simulationPosition
			);

			GD.Print(
				"Water wheel placed on Environment tile " +
				cell +
				" atlas " +
				atlasCoords +
				" -> simulation " +
				simulationPosition
			);
		}

		GD.Print(
			"Water wheels created from marker tiles: " +
			wheelStates.Count +
			"/" +
			MaxWheelCount
		);
	}

	// ============================================================
	// Viewport mapping
	// ============================================================

	private struct GameViewMapping
	{
		public SubViewportContainer GameView;
		public SubViewport SimulationViewport;
		public Camera2D Camera;

		public bool IsValid =>
			GameView != null &&
			SimulationViewport != null &&
			Camera != null;

		public Vector2 ToSimulationSpace(
			Vector2 globalPosition)
		{
			Vector2 viewportPoint =
				globalPosition -
				GameView.GlobalPosition;

			Vector2 viewportSize =
				new Vector2(
					SimulationViewport.Size.X,
					SimulationViewport.Size.Y
				);

			Vector2 screenCenter =
				viewportSize *
				0.5f;

			Vector2 cameraCenter =
				Camera.GetScreenCenterPosition();

			return
				cameraCenter +
				(
					viewportPoint -
					screenCenter
				);
		}
	}

	private GameViewMapping CreateGameViewMapping()
	{
		GameViewMapping mapping =
			new GameViewMapping();

		mapping.GameView =
			GetNodeOrNull<SubViewportContainer>(
				"../GameView"
			);

		if (
			mapping.GameView == null)
		{
			mapping.GameView =
				FindNodeOfType<SubViewportContainer>(
					GetTree().Root
				);
		}

		if (
			mapping.GameView != null)
		{
			mapping.SimulationViewport =
				mapping.GameView.GetNodeOrNull<SubViewport>(
					"SimulationViewport"
				);

			if (
				mapping.SimulationViewport == null)
			{
				foreach (
					Node child in
					mapping.GameView.GetChildren())
				{
					if (
						child is SubViewport)
					{
						mapping.SimulationViewport =
							(SubViewport)child;

						break;
					}
				}
			}
		}

		if (
			mapping.SimulationViewport != null)
		{
			mapping.Camera =
				mapping.SimulationViewport.GetNodeOrNull<Camera2D>(
					"Camera2D"
				);

			if (
				mapping.Camera == null)
			{
				mapping.Camera =
					FindNodeOfType<Camera2D>(
						mapping.SimulationViewport
					);
			}
		}

		return mapping;
	}

	// ============================================================
	// Create one wheel
	// ============================================================

	private void CreateWaterWheel(
		Vector2 center)
	{
		FluidWheelState wheelState;

		if (
			wheelStates.Count == 0)
		{
			wheelState =
				solver.CreateWheel(
					center
				);
		}
		else
		{
			wheelState =
				new FluidWheelState(
					center
				);
		}

		wheelStates.Add(
			wheelState
		);

		for (
			int i = 0;
			i < WheelBladeCount;
			i++)
		{
			float angle =
				Mathf.Tau *
				i /
				WheelBladeCount;

			Vector2 direction =
				new Vector2(
					Mathf.Cos(angle),
					Mathf.Sin(angle)
				);

			Vector2 tangent =
				new Vector2(
					-direction.Y,
					direction.X
				);

			Vector2 innerCenter =
				direction *
				WheelInnerRadius;

			Vector2 outerCenter =
				direction *
				WheelOuterRadius;

			Vector2[] blade =
			{
				innerCenter +
				tangent *
				WheelBladeWidth,

				outerCenter +
				tangent *
				WheelBladeWidth,

				outerCenter -
				tangent *
				WheelBladeWidth,

				innerCenter -
				tangent *
				WheelBladeWidth
			};

			FluidPolygonCollider collider =
				new FluidPolygonCollider(
					blade
				);

			collider.ConfigureAsWheel(
				wheelState
			);

			solver.AddPolygonCollider(
				collider
			);
		}

		const int hubSegments = 16;

		Vector2[] hub =
			new Vector2[
				hubSegments
			];

		for (
			int i = 0;
			i < hubSegments;
			i++)
		{
			float angle =
				Mathf.Tau *
				i /
				hubSegments;

			hub[i] =
				new Vector2(
					Mathf.Cos(angle),
					Mathf.Sin(angle)
				) *
				WheelInnerRadius;
		}

		FluidPolygonCollider hubCollider =
			new FluidPolygonCollider(
				hub
			);

		solver.AddPolygonCollider(
			hubCollider
		);

		WaterWheelVisual visual =
			new WaterWheelVisual();

		visual.Position =
			center;

		visual.OuterRadius =
			WheelOuterRadius;

		visual.InnerRadius =
			WheelInnerRadius;

		visual.BladeCount =
			WheelBladeCount;

		visual.BladeWidth =
			WheelBladeWidth;

		AddChild(
			visual
		);

		visual.SetWheelAngle(
			wheelState.Angle
		);

		wheelVisuals.Add(
			visual
		);
	}

	// ============================================================
	// Additional wheel physics
	// ============================================================

	private void StepAdditionalWheels(
		float dt)
	{
		for (
			int i = 1;
			i < wheelStates.Count;
			i++)
		{
			wheelStates[i].Step(
				dt
			);
		}
	}

	// ============================================================
	// Update wheel visuals
	// ============================================================

	private void UpdateWheelVisuals()
	{
		int count =
			Math.Min(
				wheelStates.Count,
				wheelVisuals.Count
			);

		for (
			int i = 0;
			i < count;
			i++)
		{
			wheelVisuals[i].SetWheelAngle(
				wheelStates[i].Angle
			);
		}
	}

	// ============================================================
	// Rain
	// ============================================================

	private void InitializeDynamicRain()
	{
		SelectNewRainPhase();
	}

	private void SelectNewRainPhase()
	{
		int stepCount =
			(RainMaximumPercent - RainMinimumPercent) /
			RainPercentStep + 1;

		int randomStep =
			rainRandom.RandiRange(0, stepCount - 1);

		currentRainPercent =
			RainMinimumPercent +
			randomStep * RainPercentStep;

		rainPhaseTimer =
			rainRandom.RandfRange(
				RainMinimumDuration,
				RainMaximumDuration
			);

		GD.Print(
			"RAIN CHANGE -> " +
			currentRainPercent +
			"% for " +
			rainPhaseTimer.ToString("F1") +
			"s"
		);
	}

	private void UpdateDynamicRain(float dt)
	{
		rainPhaseTimer -= dt;

		if (rainPhaseTimer <= 0.0f)
		{
			SelectNewRainPhase();
		}
	}

	private void SpawnRainParticle(
		float dt)
	{
		UpdateDynamicRain(dt);

		// RainAmount = 100.0f is 50% rain.
		// Therefore: percentage / 50 gives the multiplier.
		float currentRainAmount =
			RainAmount *
			(currentRainPercent / 50.0f);

		if (
			particles.Count >=
			particles.Capacity)
		{
			return;
		}

		rainSpawnAccumulator +=
			currentRainAmount *
			dt;

		int spawnCount =
			(int)rainSpawnAccumulator;

		if (
			spawnCount <= 0)
		{
			return;
		}

		rainSpawnAccumulator -=
			spawnCount;

		for (
			int i = 0;
			i < spawnCount;
			i++)
		{
			if (
				particles.Count >=
				particles.Capacity)
			{
				break;
			}

			float x =
				rainRandom.RandfRange(
					WorldMinX,
					WorldMaxX
				);

			particles.AddParticle(
				x,
				RainSpawnY,
				RainVelocityX,
				RainVelocityY
			);

			totalRainSpawns++;
		}
	}

	// ============================================================
	// Despawn particles at outer edges
	// ============================================================
	//
	// Particles are permanently removed from the active set.
	//
	// IMPORTANT:
	//
	// ParticleData.RemoveParticle(index) moves the last active
	// particle into the removed slot and decreases Count.
	//
	// Therefore, after removing index i, we MUST NOT increment i.
	// The new particle occupying index i has not been checked yet.
	// ============================================================

	private void RemoveParticlesAtOuterEdges()
	{
		int i = 0;

		while (
			i < particles.Count)
		{
			float x =
				particles.PosX[i];

			float y =
				particles.PosY[i];

			bool outside =
				x <= DespawnLeftX ||
				x >= DespawnRightX ||
				y >= DespawnBottomY;

			if (
				outside)
			{
				particles.RemoveParticle(
					i
				);

				// Do NOT increment i.
				//
				// RemoveParticle() moved the previous last
				// active particle into this slot.
				continue;
			}

			i++;
		}
	}

	// ============================================================
	// Density field
	// ============================================================

	private void BuildDensityField()
	{
		densityField.Clear();

		for (
			int i = 0;
			i < particles.Count;
			i++)
		{
			densityField.AddParticle(
				particles.PosX[i],
				particles.PosY[i]
			);
		}
	}

	// ============================================================
	// Full profiler output
	// ============================================================

	private void PrintFullProfiler()
	{
		double frameCount =
			fullProfilerFrames;

		double physicsMs =
			fullPhysicsTime /
			frameCount;

		double spawnMs =
			fullSpawnTime /
			frameCount;

		double pbfMs =
			fullPbfTime /
			frameCount;

		double densityMs =
			fullDensityTime /
			frameCount;

		double rendererMs =
			fullRendererTime /
			frameCount;

		double rendererBuildPixelsMs =
			fullRendererBuildPixelsTime /
			frameCount;

		double rendererSurfaceGlowMs =
			fullRendererSurfaceGlowTime /
			frameCount;

		double rendererFillBytesMs =
			fullRendererFillBytesTime /
			frameCount;

		double rendererTextureUploadMs =
			fullRendererTextureUploadTime /
			frameCount;

		double measuredWork =
			spawnMs +
			pbfMs +
			densityMs +
			rendererMs;

		double otherMs =
			physicsMs -
			measuredWork;

		if (
			otherMs < 0.0)
		{
			otherMs = 0.0;
		}

		double fps =
			Engine.GetFramesPerSecond();

		double physicsFps =
			physicsMs > 0.001
				? 1000.0 / physicsMs
				: 0.0;

		GD.Print(
			"========================================"
		);

		GD.Print(
			"FULL FRAME PROFILER " +
			"(avg over " +
			fullProfilerFrames +
			" physics frames)"
		);

		// --------------------------------------------------------
		// Particle statistics
		// --------------------------------------------------------

		GD.Print(
			"ActiveParticles=" +
			particles.Count +
			"/" +
			particles.Capacity
		);

		GD.Print(
			"ParticleCapacity=" +
			ParticleCount
		);

		GD.Print(
			"TotalRainSpawns=" +
			totalRainSpawns
		);

		GD.Print(
			"RenderedFPS=" +
			fps.ToString("F1")
		);

		GD.Print(
			"PhysicsFPS=" +
			physicsFps.ToString("F1")
		);

		GD.Print(
			"PhysicsProcess=" +
			physicsMs.ToString("F2") +
			"ms"
		);

		GD.Print(
			"  Spawn=" +
			spawnMs.ToString("F2") +
			"ms"
		);

		GD.Print(
			"  PBF=" +
			pbfMs.ToString("F2") +
			"ms"
		);

		GD.Print(
			"  Density=" +
			densityMs.ToString("F2") +
			"ms"
		);

		GD.Print(
			"  Renderer=" +
			rendererMs.ToString("F2") +
			"ms"
		);

		GD.Print(
			"    BuildPixels=" +
			rendererBuildPixelsMs.ToString("F2") +
			"ms"
		);

		GD.Print(
			"    SurfaceGlow=" +
			rendererSurfaceGlowMs.ToString("F2") +
			"ms"
		);

		GD.Print(
			"    FillBytes=" +
			rendererFillBytesMs.ToString("F2") +
			"ms"
		);

		GD.Print(
			"    TextureUpload=" +
			rendererTextureUploadMs.ToString("F2") +
			"ms"
		);

		GD.Print(
			"  Other=" +
			otherMs.ToString("F2") +
			"ms"
		);

		GD.Print(
			"MeasuredWork=" +
			measuredWork.ToString("F2") +
			"ms"
		);

		// --------------------------------------------------------
		// Energy statistics
		// --------------------------------------------------------

		GD.Print(
			"Energy=" +
			energySystem.Energy.ToString("F2")
		);

		GD.Print(
			"EnergyThisFrame=" +
			energyGeneratedThisFrame.ToString("F2")
		);

		double energyPerSecond =
			lastPhysicsDelta > 0.000001f
				? energyGeneratedThisFrame /
					lastPhysicsDelta
				: 0.0;

		GD.Print(
			"EnergyPerSecond=" +
			energyPerSecond.ToString("F2")
		);

		GD.Print(
			"TotalEnergyGenerated=" +
			energySystem.TotalGenerated.ToString("F2")
		);

		// --------------------------------------------------------
		// Individual wheel energy
		// --------------------------------------------------------

		for (
			int i = 0;
			i < wheelStates.Count;
			i++)
		{
			double wheelEnergy =
				i <
				wheelEnergyGeneratedThisFrame.Length
					? wheelEnergyGeneratedThisFrame[i]
					: 0.0;

			double wheelEnergyPerSecond =
				lastPhysicsDelta > 0.000001f
					? wheelEnergy /
						lastPhysicsDelta
					: 0.0;

			GD.Print(
				"Wheel " +
				(i + 1) +
				" EnergyThisFrame=" +
				wheelEnergy.ToString("F4") +
				" EnergyPerSecond=" +
				wheelEnergyPerSecond.ToString("F4")
			);
		}

		GD.Print(
			"========================================"
		);
	}

	// ============================================================
	// Reset profiler
	// ============================================================

	private void ResetFullProfiler()
	{
		fullProfilerFrames = 0;

		fullPhysicsTime = 0.0;

		fullSpawnTime = 0.0;
		fullPbfTime = 0.0;
		fullDensityTime = 0.0;
		fullRendererTime = 0.0;

		fullRendererBuildPixelsTime = 0.0;
		fullRendererSurfaceGlowTime = 0.0;
		fullRendererFillBytesTime = 0.0;
		fullRendererTextureUploadTime = 0.0;
	}
}
